export { default as UserDetails } from './UserDetails';
export { default as CustomerDataManagement } from './CustomerDataManagement';
export { default as UserEditForm } from './UserEditForm';
export { default as UserUpdateLimit } from './UserUpdateLimit';
export { default as CustomerInvoices } from './CustomerInvoices';
export { default as UserBankDetails } from './UserBankDetails';
export { default as CustomerListTable } from './UsersTable';
export { default as CustomerLogs } from './CustomerLogs';
export { default as UserSwapMobileNumber } from './UserSwapMobileNumber';
