version: 2.1

orbs:
  aws-cli: circleci/aws-cli@2.0.0
  node: circleci/node@4.2.1

jobs:
  build:
    executor:
      name: node/default
      tag: '14.15.5'
    parameters:
      env:
        type: string
        default: dev
    steps:
      - checkout
      - node/install-packages
      - run:
          name: Build
          command: make lint test build ENV=<<parameters.env>>
      - store_artifacts:
          path: ./build
      - persist_to_workspace:
          root: .
          paths:
            - './build/*'

  deploy:
    executor:
      name: aws-cli/default
    parameters:
      env:
        type: string
        default: dev
    steps:
      - checkout
      - node/install-packages
      - attach_workspace:
          at: '.'
      - aws-cli/setup
      - run:
          # AWS assume role missing https://github.com/CircleCI-Public/aws-cli-orb/issues/57
          name: Configure AWS Assume Role
          command: |-
            aws configure set profile.<<parameters.env>>.role_arn "$AWS_ROLE_ARN"
            aws configure set profile.<<parameters.env>>.source_profile default
      - run:
          name: Deploy
          command: make deploy ENV=<<parameters.env>>

workflows:
  build-deploy-dev:
    jobs:
      - build:
          env: dev
          filters:
            branches:
              only: develop
      - deploy:
          name: deploy
          context: dev
          env: dev
          filters:
            branches:
              only: develop
          requires:
            - build
  build-deploy-staging:
    jobs:
      - build:
          env: staging
          filters:
            branches:
              only: master
      - deploy:
          context: staging
          env: staging
          filters:
            branches:
              only: master
          requires:
            - build
